### ISSUE TITLE
airs-bp3/apps/untill/airsbp: vpm compile panics if APPLICATION is removed

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1201] opened 2023-12-25 09:40 UTC
```javascript
IMPORT SCHEMA 'github.com/untillpro/airs-scheme/bp3' AS untill;
IMPORT SCHEMA 'github.com/untillpro/airs-bp3/packages/air';

APPLICATION airsbp ( <-- remove this one
	USE untill;
	USE air;
);
```

**Comment by host6** [comment] 2023-12-25 10:45
duplicate of #1193

**Closed by host6** 2023-12-25 10:45 UTC
Labels: prty/blocker
