### ISSUE TITLE
Daily Test failed on 09/07/2024 05:13

### ISSUE THREAD

**Issue by ivvist** [voedger/voedger#2347] opened 2024-07-09 05:13 UTC
https://github.com/voedger/voedger/actions/runs/9851331273
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2348
```

**Comment by host6** [comment] 2024-07-23 08:59
duplicate of #2384

**Closed by host6** 2024-07-23 08:59 UTC
Labels: kind/bug
